# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 12:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=125, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid user', message='first name must be alphabetic', regex='^[a-zA-X]*$')])),
                ('first_name', models.CharField(max_length=125, validators=[django.core.validators.RegexValidator(code='Invalid first name', message='first name must be alphabetic', regex='^[a-zA-X]*$')])),
                ('last_name', models.CharField(max_length=125, validators=[django.core.validators.RegexValidator(code='Invalid last name', message='last name must be alphabetic', regex='^[a-zA-X]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
