# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180927_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
