# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 10:03
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[blog.models.validate_author_email]),
        ),
    ]
