# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180927_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'unique': 'title has to be unique'}, max_length=50, unique=True),
        ),
    ]
