# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181005_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.TextField(max_length=500),
        ),
    ]
